video_player1:
  ros__parameters:
    config_found: true
    publish_frequency: 30.0
    topic: /video_player1/image
    # filename: /home/maimon/eternarig_ws/src/video_interface/videos/fictrac_bee.mp4
    # filename: /home/maimon/eternarig_ws/src/video_interface/videos/maimon_fruitfly.avi
    filename: /home/maimon/eternarig_ws/src/video_interface/videos/topview_4arena.avi
    # filename: /home/maimon/src/record_h264/video_20200901_033706_cam18517933-000.mp4"
    # loop_play: true
    loop_play: false

video_saver1:
  ros__parameters:
    config_found: true
    topic: /video_player1/image
    # output_filename: /home/maimon/eternarig_ws/src/video_interface/data/fictrac_bee.avi
    # output_filename: /home/maimon/eternarig_ws/src/video_interface/data/fruitfly_compressed.avi
    # output_filename: /home/maimon/eternarig_ws/src/video_interface/data/topview_4arena.avi
    output_filename: /home/maimon/eternarig_ws/src/video_interface/data/test_to_compress.avi
